Traceback because of getRetested attribute (#50)
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module senaite.impress.decorators, line 41, in decorator
  Module senaite.impress.ajax, line 64, in __call__
  Module senaite.impress.ajax, line 175, in ajax_render_reports
  Module senaite.impress.publishview, line 189, in render_multi_report
  Module senaite.impress.publishview, line 306, in read_template
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 158, in render
  Module chameleon.zpt.template, line 297, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module c294303fcc7a675ae1f8f1e86b516f16.py, line 3834, in render
  Module senaite.impress.analysisrequest.model, line 44, in is_retested
  Module senaite.core.supermodel.model, line 105, in __getattr__
AttributeError: getRetested